const sampleListings = [
    {
      title: "Fresh Organic Carrots",
      description: "Locally grown, pesticide-free carrots. Crisp and sweet, perfect for snacking or cooking.",
      image: "carrot_image_url", 
      price: 25, 
      location: "Farmville, Anytown",
      category: "Vegetables",
      owner: "Nouman",
    },
    {
      title: "Ripe Juicy Mangoes",
      description: "Sun-ripened Alphonso mangoes, known for their rich flavor and sweetness.",
      image: "mango_image_url",
      price: 75, 
      location: "Sunny Orchards, Anytown",
      category: "Fruits",
      owner: "Nouman",
    },
    {
      title: "Premium Basmati Rice",
      description: "Aromatic and long-grain Basmati rice, ideal for biryanis and other rice dishes.",
      image: "rice_image_url",
      price: 60, 
      location: "Green Fields Farm, Anytown",
      category: "Grains",
      owner: "Nouman",
    },
    {
      title: "Healthy Broccoli Florets",
      description: "Freshly harvested broccoli florets, packed with vitamins and nutrients.",
      image: "broccoli_image_url",
      price: 35,
      location: "Healthy Harvest Farm, Anytown",
      category: "Vegetables",
      owner: "Nouman",
    },
    {
      title: "Sweet and Tangy Oranges",
      description: "Juicy and refreshing oranges, perfect for a healthy snack or juice.",
      image: "orange_image_url",
      price: 40, 
      location: "Citrus Grove, Anytown",
      category: "Fruits",
      owner: "Nouman",
    },
    {
      title: "Whole Wheat Flour",
      description: "Stone-ground whole wheat flour, perfect for baking bread and other goods.",
      image: "flour_image_url",
      price: 50, 
      location: "Grain Mill, Anytown",
      category: "Grains",
      owner: "Nouman",
    },
    {
      title: "Farm-Fresh Eggs",
      description: "Free-range chicken eggs, rich in protein and flavor.",
      image: "egg_image_url",
      price: 10, 
      location: "Happy Hen Farm, Anytown",
      category: "Poultry",
      owner: "Nouman",
    },
    {
      title: "Organic Spinach",
      description: "Fresh and leafy spinach, packed with iron and other essential nutrients.",
      image: "spinach_image_url",
      price: 20, 
      location: "Green Leaf Farm, Anytown",
      category: "Vegetables",
      owner: "Nouman",
    },
    {
      title: "Red Delicious Apples",
      description: "Crisp and sweet red apples, perfect for snacking or baking.",
      image: "apple_image_url",
      price: 55,
      location: "Apple Orchard, Anytown",
      category: "Fruits",
      owner: "Nouman",
    },
    {
      title: "Brown Rice",
      description: "Nutritious and fiber-rich brown rice, a healthy alternative to white rice.",
      image: "brown_rice_image_url",
      price: 45, 
      location: "Healthy Grains Farm, Anytown",
      category: "Grains",
      owner: "Nouman",
    },
      {
      title: "Free-Range Chicken",
      description: "Whole, unprocessed free-range chicken, ready for cooking.",
      image: "chicken_image_url",
      price: 120, 
      location: "Countryside Farm, Anytown",
      category: "Poultry",
      owner: "Nouman",
    },
    {
      title: "Freshly Picked Strawberries",
      description: "Juicy and sweet strawberries, perfect for desserts or snacking.",
      image: "strawberry_image_url",
      price: 60, 
      location: "Berry Patch Farm, Anytown",
      category: "Fruits",
      owner: "Nouman",
    },
    {
      title: "Oats",
      description: "Rolled oats, a healthy and versatile grain for breakfast or baking.",
      image: "oats_image_url",
      price: 30, 
      location: "Oat Fields, Anytown",
      category: "Grains",
      owner: "Nouman",
    },
    {
      title: "Lettuce",
      description: "Crisp and fresh lettuce, perfect for salads and sandwiches.",
      image: "lettuce_image_url",
      price: 15, 
      location: "Salad Greens Farm, Anytown",
      category: "Vegetables",
      owner: "Nouman",
    },
    {
      title: "Bananas",
      description: "Ripe and creamy bananas, a healthy and convenient snack.",
      image: "banana_image_url",
      price: 20, 
      location: "Tropical Farms, Anytown",
      category: "Fruits",
      owner: "Nouman",
    }, {
      title: "Organic Green Beans",
      description: "Freshly picked, crisp green beans.",
      image: "green_beans_image_url",
      price: 30,
      location: "Bean Fields",
      category: "Vegetables",
      owner: "Nouman",
    },
    {
      title: "Blueberries",
      description: "Sweet and juicy blueberries.",
      image: "blueberries_image_url",
      price: 80,
      location: "Blueberry Hill",
      category: "Fruits",
      owner: "Nouman",
    },
    {
      title: "Rye Flour",
      description: "Dark and flavorful rye flour.",
      image: "rye_flour_image_url",
      price: 65,
      location: "Rye Mill",
      category: "Grains",
      owner: "Nouman",
    },
    {
      title: "Turkey",
      description: "Whole, unprocessed turkey.",
      image: "turkey_image_url",
      price: 150,
      location: "Turkey Farm",
      category: "Poultry",
      owner: "Nouman",
    },
    {
      title: "Raspberries",
      description: "Tart and delicious raspberries.",
      image: "raspberries_image_url",
      price: 70,
      location: "Raspberry Patch",
      category: "Fruits",
      owner: "Nouman",
    },
    {
      title: "Barley",
      description: "Pearl barley.",
      image: "barley_image_url",
      price: 40,
      location: "Barley Fields",
      category: "Grains",
      owner: "Nouman",
    },
    {
      title: "Pears",
      description: "Juicy and sweet pears.",
      image: "pears_image_url",
      price: 50,
      location: "Pear Orchard",
      category: "Fruits",
      owner: "Nouman",
    },
    {
      title: "Couscous",
      description: "Fine semolina couscous.",
      image: "couscous_image_url",
      price: 55,
      location: "Couscous Mill",
      category: "Grains",
      owner: "Nouman",
    },
    {
      title: "Goose Eggs",
      description: "Large and rich goose eggs.",
      image: "goose_eggs_image_url",
      price: 20,
      location: "Goose Farm",
      category: "Poultry",
      owner: "Nouman",
    },
    {
      title: "Kale",
      description: "Nutritious and leafy kale.",
      image: "kale_image_url",
      price: 25,
      location: "Kale Farm",
      category: "Vegetables",
      owner: "Nouman",
    },
    {
      title: "Plums",
      description: "Sweet and juicy plums.",
      image: "plums_image_url",
      price: 60,
      location: "Plum Orchard",
      category: "Fruits",
      owner: "Nouman",
    },
    {
      title: "Spelt Flour",
      description: "Nutty and slightly sweet spelt flour.",
      image: "spelt_flour_image_url",
      price: 75,
      location: "Spelt Mill",
      category: "Grains",
      owner: "Nouman",
    },
    {
      title: "Guinea Fowl",
      description: "Lean and flavorful guinea fowl.",
      image: "guinea_fowl_image_url",
      price: 100,
      location: "Guinea Fowl Farm",
      category: "Poultry",
      owner: "Nouman",
    },
    {
      title: "Radishes",
      description: "Crisp and peppery radishes.",
      image: "radishes_image_url",
      price: 15,
      location: "Radish Farm",
      category: "Vegetables",
      owner: "Nouman",
    },
    {
      title: "Cherries",
      description: "Sweet and tart cherries.",
      image: "cherries_image_url",
      price: 90,
      location: "Cherry Orchard",
      category: "Fruits",
      owner: "Nouman",
    },

];

module.exports = { data: sampleListings };